<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="test"
    errors="1" failures="0" hostname="" id="" package="test" skipped="0"
    tests="1" time="0.02900" timestamp="Tue, 22 May 2018 14:08:21 GMT">
  
    <testcase name="default autharisation error test" classname="test" time="0.02900" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Test / default autharisation error test]:

  ReferenceError: sas is not defined
    at Object.default autharisation error test (/home/evg/WebstormProjects/demo_alehub_wallet/test/e2e/specs/test.js:11:49)
    at Module.call (/home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/home/evg/WebstormProjects/demo_alehub_wallet/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
    </system-err>
  

  
  </testsuite>
</testsuites>
